# Generated by Django 4.1.7 on 2023-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name_of_the_link')),
                ('number', models.CharField(max_length=40, verbose_name='Phone_number')),
            ],
            options={
                'verbose_name': 'Phone',
            },
        ),
    ]
