# Generated by Django 4.1.7 on 2023-02-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name_of_the_link')),
                ('text', models.TextField(verbose_name='Phone_number')),
                ('begin', models.CharField(max_length=40, verbose_name='Begining text')),
                ('img', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
    ]
