# Generated by Django 4.1.7 on 2023-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='bigimg',
            field=models.ImageField(default=1, upload_to=None, verbose_name='BigImage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hello',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Hello'),
        ),
        migrations.AlterField(
            model_name='hello',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
