# Generated by Django 4.1.7 on 2023-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Count')),
                ('info', models.CharField(max_length=240, verbose_name='Info')),
            ],
        ),
    ]
