# Generated by Django 4.1.7 on 2023-02-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_all_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='Fourth_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='Second_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('price', models.CharField(max_length=240, verbose_name='Price')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
    ]
